name: Build
on:
    push:
      branches: [main]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
    #   - name: Install dependencies
    #     run: npm ci
    #   - name: Npm run ESLint
    #     run: npm run lint
      - name: Show file structure
        run: ls -la
      - name: Show Docker version
        run: docker -v
    #   - name: Show current directory
    #     run: pwd
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
            file: Dockerfile
            push: false
            tags: user/app:latest
